const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

const portal = $('#portal');
const app = $('.app-shell');
const portalContent = $('#portalContent');
const portalNav = $('#portalNav');
const portalLabel = $('#portalLabel');
const portalBreadcrumb = $('#portalBreadcrumb');
let activeRole = 'client';
let currentView = 'overview';

const icons = { overview: '⌂', meals: '☕', progress: '↗', calls: '◷', reports: '▣', clients: '♙', builder: '⌁', recipes: '🍽', enquiries: '◎', insights: '◔' };
const roleMenu = {
  client: [['overview','Overview'],['meals',"This week's meals"],['progress','My progress'],['calls','Calls'],['reports','Reports']],
  dietitian: [['overview','Dashboard'],['clients','Clients'],['builder','Weekly plan'],['recipes','Recipe library'],['calls','Schedule calls'],['reports','Report reviews']],
  admin: [['overview','Business overview'],['enquiries','Enquiry pipeline'],['clients','Clients'],['builder','Weekly plan'],['recipes','Recipe library'],['insights','Growth insights']]
};

const lineChart = (large = false) => `<svg class="progress-svg" viewBox="0 0 650 ${large ? 260 : 140}" role="img" aria-label="Weight trend reducing consistently from 72 to 67.8 kilograms"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#91b68d" stop-opacity=".35"/><stop offset="1" stop-color="#91b68d" stop-opacity="0"/></linearGradient></defs><g stroke="#dbe5d8" stroke-width="1"><line x1="38" y1="20" x2="630" y2="20"/><line x1="38" y1="${large ? 105 : 65}" x2="630" y2="${large ? 105 : 65}"/><line x1="38" y1="${large ? 190 : 110}" x2="630" y2="${large ? 190 : 110}"/></g><path d="M42,${large?32:27} C102,${large?48:37} 111,${large?54:42} 150,${large?62:48} S215,${large?76:56} 250,${large?79:61} S323,${large?111:78} 352,${large?115:84} S420,${large?134:92} 450,${large?144:97} S520,${large?155:104} 546,${large?168:109} S592,${large?173:111} 620,${large?181:114} L620,${large?190:110} L42,${large?190:110} Z" fill="url(#area)"/><path d="M42,${large?32:27} C102,${large?48:37} 111,${large?54:42} 150,${large?62:48} S215,${large?76:56} 250,${large?79:61} S323,${large?111:78} 352,${large?115:84} S420,${large?134:92} 450,${large?144:97} S520,${large?155:104} 546,${large?168:109} S592,${large?173:111} 620,${large?181:114}" fill="none" stroke="#5f966c" stroke-width="3" stroke-linecap="round"/><g fill="#fff" stroke="#5f966c" stroke-width="3"><circle cx="42" cy="${large?32:27}" r="4"/><circle cx="250" cy="${large?79:61}" r="4"/><circle cx="450" cy="${large?144:97}" r="4"/><circle cx="620" cy="${large?181:114}" r="5"/></g><text x="626" y="${large?178:112}" fill="#2f6a49" font-family="DM Sans" font-size="12" font-weight="700">67.8 kg</text></svg>`;

function clientOverview(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Good morning, Priya. You’re doing great—keep going!</p><h1>Your wellness dashboard</h1><p>Here’s a gentle look at your day.</p></div><button class="btn btn-coral" onclick="setView('progress')">Update progress <span>→</span></button></div><div class="dashboard-grid"><section class="card"><div class="card-top"><h2>Today’s meals</h2><button class="link-button" onclick="setView('meals')">View all meals →</button></div><div class="today-meal"><div class="meal-picture">🥣</div><div><span class="meal-time">UP NEXT · 8:00 AM</span><h3>Berry & chia breakfast bowl</h3><p>With Greek yogurt, almonds & a drizzle of honey</p></div><button class="check-button" aria-label="Mark breakfast complete">✓</button></div><div class="quick-stats"><div class="stat-card"><span class="stat-label">Current plan</span><strong>Thrive</strong><small>48 days remaining</small></div><div class="stat-card sage-bg"><span class="stat-label">Latest weight</span><strong>67.8 kg</strong><small>↓ 0.6 kg this week</small></div></div></section><section class="card call-card"><h2>Your next check-in</h2><div class="call-date">Tuesday, 12 Aug</div><p>10:30 AM · 30 minute video call</p><div class="dietitian-mini"><div class="person-avatar avatar-rhea">R</div><div><strong>Rhea Sharma, RD</strong><span>Your dietitian</span></div></div><button>Join video call →</button></section><section class="card progress-card"><div class="card-top"><h2>Your steady progress</h2><strong style="color:#5f966c;font-size:13px">−4.2 kg</strong></div><div class="chart-wrap">${lineChart()}</div><div class="chart-labels"><span>1 Jul</span><span>15 Jul</span><span>29 Jul</span><span>Today</span></div><div class="progress-footer"><span>Small steps, real change.</span><strong>View my progress →</strong></div></section><section class="card quote-card"><div class="quote-mark">“</div><p>Consistency isn’t about being perfect. You showed up for yourself 5 days this week.</p></section><section class="card"><div class="card-top"><h2>Quick report upload</h2><span>▣</span></div><div class="report-upload"><strong>Drop a report here</strong><p>PDF, photo, or lab result · up to 10 MB</p><button>Choose a file</button></div></section></div></div>`}

function mealsView(){const meals=[['Breakfast','8:00 AM','🥣','Berry & chia breakfast bowl','Greek yogurt, berries, chia & almonds'],['Lunch','1:00 PM','🥗','Rainbow quinoa nourish bowl','Roasted vegetables, chickpeas & tahini'],['Snack','4:30 PM','🍏','Apple slices with nut butter','A satisfying little energy boost'],['Dinner','7:30 PM','🍲','Lentil & veggie comfort soup','With warm sourdough and herbs']];return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Made to nourish your Tuesday</p><h1>This week’s meals</h1><p>Tap a meal when you’ve enjoyed it. Every little tick is a win.</p></div><button class="btn btn-outline">♡ Save shopping list</button></div><div class="meals-view"><section class="card"><div class="days">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=>`<button class="day-button ${i===1?'active':''}">${d}<br><small>${11+i}</small></button>`).join('')}</div><div class="meal-list">${meals.map(m=>`<article class="meal-row card"><span class="meal-type">${m[0]}</span><div class="meal-picture">${m[2]}</div><div><span class="meal-time">${m[1]}</span><h3>${m[3]}</h3><p>${m[4]}</p></div><button class="check-button" aria-label="Mark ${m[0]} complete">✓</button></article>`).join('')}</div></section><aside class="card weekly-card"><h2>Your weekly rhythm</h2><div class="completion-ring"></div><p>You’ve completed 19 of 28 meals this week.</p><button class="btn btn-forest">View recipes</button></aside></div></div>`}

function progressView(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Look how far you’ve come</p><h1>Your progress</h1><p>Every update tells a story of care and consistency.</p></div><button class="btn btn-coral">Update today’s progress <span>→</span></button></div><div class="progress-view"><section class="card"><div class="card-top"><div><h2>Your weight trend</h2><span style="color:var(--muted);font-size:12px">A gentle downward trend over the last 6 weeks</span></div><strong style="color:#5f966c">−4.2 kg</strong></div><div class="large-chart">${lineChart(true)}</div><div class="chart-labels"><span>1 Jul</span><span>8 Jul</span><span>15 Jul</span><span>22 Jul</span><span>29 Jul</span><span>Today</span></div></section><aside class="card weekly-card"><h2>Lovely milestones</h2><div class="milestone"><i>✓</i><div><strong>5 mindful days</strong><span>You checked in with yourself this week.</span></div></div><div class="milestone"><i>✦</i><div><strong>First 4 kg celebrated</strong><span>That’s a meaningful, lasting change.</span></div></div><div class="milestone"><i>↗</i><div><strong>Strength is building</strong><span>Your energy score is up 18%.</span></div></div></aside><section class="card"><div class="card-top"><h2>Measurements</h2><button class="link-button">View details →</button></div><div class="quick-stats"><div class="stat-card sage-bg"><span class="stat-label">Waist</span><strong>78 cm</strong><small>↓ 3 cm since June</small></div><div class="stat-card"><span class="stat-label">Energy score</span><strong>8 / 10</strong><small>↑ 2 points this month</small></div></div></section></div></div>`}

function dietitianOverview(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Tuesday, 11 August</p><h1>Good morning, Rhea</h1><p>You have 5 client moments to make meaningful today.</p></div><div><button class="btn btn-outline" onclick="setView('builder')">Create diet plan</button> <button class="btn btn-coral" onclick="setView('clients')">Add client</button></div></div><div class="dashboard-grid"><section class="card"><div class="card-top"><h2>Today’s appointments</h2><button class="link-button" onclick="setView('calls')">View calendar →</button></div>${[['9:30','Priya Shah','Progress check-in'],['11:00','Kavya Menon','PCOS support'],['2:30','Aarav Kapoor','Plan review'],['5:00','Sneha Roy','New client consult']].map(a=>`<div class="appointment"><time>${a[0]}</time><div class="person-avatar avatar-rhea">${a[1][0]}</div><div><strong>${a[1]}</strong><span>${a[2]} · 30 min</span></div><button class="link-button">Open →</button></div>`).join('')}</section><section class="card"><div class="card-top"><h2>Needs your attention</h2><span>◎</span></div><div class="milestone"><i>!</i><div><strong>3 reports to review</strong><span>Latest upload: Neel’s lipid panel</span></div></div><div class="milestone"><i>⌁</i><div><strong>2 missed check-ins</strong><span>Send a gentle follow-up today</span></div></div><div class="milestone"><i>↗</i><div><strong>Priya hit a milestone</strong><span>Celebrate her 4 kg progress</span></div></div></section><section class="card progress-card"><div class="card-top"><h2>Client momentum</h2><span class="progress-pill">86% on track</span></div><div class="chart-wrap">${lineChart()}</div><div class="progress-footer"><span>38 active clients this month</span><strong>View clients →</strong></div></section><section class="card quote-card"><div class="quote-mark">“</div><p>“Rhea, I finally feel like I can do this.” — A message from Priya</p></section></div></div>`}

const clients = [['Priya Shah','Thrive','Weight loss','68%','Today'],['Kavya Menon','Flourish','PCOS','82%','Today'],['Aarav Kapoor','Fresh Start','Sports nutrition','54%','Tomorrow'],['Neel Sharma','Thrive','Diabetes support','74%','14 Aug']];
function clientsView(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">38 people in your care</p><h1>Your clients</h1><p>Stay close to the progress that matters.</p></div><button class="btn btn-coral">Add a client <span>+</span></button></div><section class="card"><div class="card-top"><h2>Client list</h2><input class="search-input" placeholder="Search clients…" /></div><div style="overflow:auto"><table class="clients-table"><thead><tr><th>Client</th><th>Plan</th><th>Goal</th><th>Progress</th><th>Next call</th><th></th></tr></thead><tbody>${clients.map((c,i)=>`<tr><td><div style="display:flex;align-items:center;gap:8px"><div class="person-avatar avatar-${i%2?'nisha':'priya'}" style="width:28px;height:28px;flex-basis:28px;font-size:12px">${c[0][0]}</div><strong>${c[0]}</strong></div></td><td>${c[1]}</td><td>${c[2]}</td><td><span class="progress-pill">${c[3]} complete</span></td><td>${c[4]}</td><td><button class="link-button">Profile →</button></td></tr>`).join('')}</tbody></table></div></section></div>`}

const recipes=[{id:'berry',emoji:'🥣',name:'Berry & chia breakfast bowl',meal:'Breakfast',time:'10 min',tags:['High protein','Vegetarian']},{id:'quinoa',emoji:'🥗',name:'Rainbow quinoa nourish bowl',meal:'Lunch',time:'20 min',tags:['Fibre rich','Vegan']},{id:'lentil',emoji:'🍲',name:'Lentil & veggie comfort soup',meal:'Dinner',time:'30 min',tags:['Gut friendly','Vegan']},{id:'paneer',emoji:'🍛',name:'Herbed paneer grain bowl',meal:'Lunch',time:'25 min',tags:['High protein','Gluten free']},{id:'apple',emoji:'🍏',name:'Apple slices with nut butter',meal:'Snack',time:'5 min',tags:['Quick','Vegetarian']}];
const weekRows=[['Monday','08:00 AM','Breakfast','Berry & chia breakfast bowl'],['Tuesday','01:00 PM','Lunch','Rainbow quinoa nourish bowl'],['Wednesday','07:30 PM','Dinner','Lentil & veggie comfort soup'],['Thursday','08:00 AM','Breakfast',''],['Friday','01:00 PM','Lunch',''],['Saturday','07:30 PM','Dinner',''],['Sunday','08:30 AM','Breakfast','']];
function recipeCard(recipe,compact=false){return `<article class="recipe-card ${compact?'compact':''}" draggable="true" ondragstart="startRecipeDrag(event,'${recipe.id}')"><div class="recipe-emoji">${recipe.emoji}</div><div class="recipe-card-copy"><strong>${recipe.name}</strong><span>${recipe.meal} · ${recipe.time}</span>${compact?'':`<div>${recipe.tags.map(tag=>`<small>${tag}</small>`).join('')}</div>`}</div><span class="drag-handle" aria-label="Drag recipe">⠿</span></article>`}
function builderView(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Weekly diet schedule</p><h1>Assign a weekly diet</h1><p>Set the client, timing, and meals—then drag recipes from the library into the plan.</p></div><button class="btn btn-coral" onclick="publishPlan()">Publish weekly plan <span>→</span></button></div><section class="plan-builder-layout"><div class="card schedule-panel"><div class="schedule-fields"><label>Customer<select><option>Priya Shah</option><option>Kavya Menon</option><option>Aarav Kapoor</option></select></label><label>Week starts<input type="date" value="2026-08-11" /></label><label>Plan title<input value="Priya's weekly nourish plan" /></label></div><div class="schedule-heading"><div><h2>Meal schedule</h2><p>Drag a recipe onto any meal slot, or select a recipe to add it.</p></div><button class="link-button" onclick="addMealRow()">+ Add meal</button></div><div class="schedule-list" id="scheduleList">${weekRows.map((row,index)=>scheduleRow(row,index)).join('')}</div></div><aside class="card recipe-rail"><div class="rail-heading"><div><h2>Recipe library</h2><span>Drag into the schedule</span></div><button class="link-button" onclick="setView('recipes')">Manage recipes →</button></div><input class="recipe-search" placeholder="Search recipes" oninput="filterRecipes(this.value)" /><div class="recipe-filters"><button class="active">All</button><button>Breakfast</button><button>Lunch</button><button>Dinner</button></div><div class="recipe-rail-list" id="recipeRailList">${recipes.map(recipe=>recipeCard(recipe,true)).join('')}</div><button class="create-recipe-link" onclick="setView('recipes')">＋ Create a new recipe</button></aside></section></div>`}
function scheduleRow(row,index){const [day,time,type,meal]=row;return `<div class="schedule-row" data-row="${index}"><select aria-label="Day"><option>${day}</option><option>Monday</option><option>Tuesday</option><option>Wednesday</option><option>Thursday</option><option>Friday</option><option>Saturday</option><option>Sunday</option></select><input aria-label="Time" value="${time}" /><select aria-label="Meal type"><option>${type}</option><option>Breakfast</option><option>Lunch</option><option>Snack</option><option>Dinner</option></select><div class="recipe-dropzone ${meal?'filled':''}" ondragover="event.preventDefault();this.classList.add('over')" ondragleave="this.classList.remove('over')" ondrop="dropRecipe(event,this)">${meal?`<strong>${meal}</strong><span>Recipe selected</span>`:'Drop a recipe here'}</div><button class="remove-meal" aria-label="Remove meal" onclick="this.parentElement.remove()">×</button></div>`}
function recipesView(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Shared by your whole care team</p><h1>Recipe library</h1><p>Create practical, nourishing recipes once and use them in every weekly plan.</p></div><button class="btn btn-coral" onclick="showRecipeForm()">Create recipe <span>+</span></button></div><section class="card recipe-creator hidden" id="recipeCreator"><div class="card-top"><div><h2>Create a recipe</h2><span class="recipe-help">This will be available to Dietitians and Admins.</span></div><button class="link-button" onclick="hideRecipeForm()">Close</button></div><form class="creator-grid" onsubmit="saveRecipe(event)"><label>Recipe name<input required name="recipeName" placeholder="e.g. Spinach & feta omelette" /></label><label>Meal type<select name="mealType"><option>Breakfast</option><option>Lunch</option><option>Snack</option><option>Dinner</option></select></label><label>Preparation time<input required name="prepTime" placeholder="e.g. 15 min" /></label><label>Ingredients<textarea required name="ingredients" placeholder="List the ingredients clients need"></textarea></label><label>Simple instructions<textarea required name="instructions" placeholder="Keep steps clear and encouraging"></textarea></label><button class="btn btn-forest" type="submit">Save recipe</button></form></section><section class="recipe-library-grid">${recipes.map(recipe=>recipeCard(recipe)).join('')}</section></div>`}

function adminOverview(){return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">Business pulse · August 2026</p><h1>Your clinic at a glance</h1><p>Warm care is growing—here’s what needs your attention.</p></div><button class="btn btn-coral" onclick="setView('enquiries')">View enquiries <span>→</span></button></div><div class="admin-metrics"><div class="card admin-metric"><span>New enquiries</span><strong>86</strong><small style="color:#5f966c">↑ 12% this month</small></div><div class="card admin-metric"><span>Follow-ups today</span><strong>12</strong><small style="color:#ec7958">4 need attention</small></div><div class="card admin-metric"><span>Conversion rate</span><strong>31%</strong><small style="color:#5f966c">↑ 4.8% vs July</small></div><div class="card admin-metric"><span>Active clients</span><strong>248</strong><small style="color:#5f966c">↑ 16 this month</small></div></div><div class="admin-layout"><section class="card"><div class="card-top"><h2>Growth over the last 6 weeks</h2><span class="progress-pill">On track</span></div><div class="large-chart">${lineChart(true)}</div><div class="chart-labels"><span>1 Jul</span><span>8 Jul</span><span>15 Jul</span><span>22 Jul</span><span>29 Jul</span><span>Today</span></div></section><section class="card"><div class="card-top"><h2>Dietitian workload</h2><button class="link-button">Manage →</button></div>${[['Rhea Sharma','38 clients','91%'],['Arjun Mehta','34 clients','84%'],['Nisha Patel','29 clients','72%']].map(d=>`<div class="appointment"><div class="person-avatar avatar-rhea">${d[0][0]}</div><div style="flex:1"><strong>${d[0]}</strong><span>${d[1]} · ${d[2]} capacity</span></div><span class="progress-pill">Balanced</span></div>`).join('')}</section></div></div>`}

function enquiriesView(){const cols=[['New enquiry',['Meera K.','Harsh V.']],['Contacted',['Kritika S.']],['Follow-up',['Varun P.','Isha M.']],['Converted',['Nikhil R.']],['Closed',['Tanvi G.']]];return `<div class="portal-page"><div class="page-title-row"><div><p class="page-greeting">86 new conversations this month</p><h1>Enquiry pipeline</h1><p>Move a card to keep every person feeling seen.</p></div><button class="btn btn-outline">+ Add enquiry</button></div><section class="card"><div class="pipeline">${cols.map(([title, leads])=>`<div class="pipeline-column" data-stage="${title}" ondragover="event.preventDefault()" ondrop="moveLead(event,this)"><h3>${title} · ${leads.length}</h3>${leads.map((name,i)=>`<div class="lead" draggable="true" ondragstart="event.dataTransfer.setData('text', event.currentTarget.outerHTML); event.currentTarget.remove()"><strong>${name}</strong><span>${i%2?'PCOS support':'Weight loss'}</span><span class="lead-source">${i%2?'Instagram':'Website'}</span></div>`).join('')}</div>`).join('')}</div></section></div>`}

const noView = () => `<div class="portal-page"><p class="page-greeting">In progress</p><h1>Coming together beautifully</h1><p>This view is ready for your team’s live data.</p></div>`;
function renderPortal(){const renderers={client:{overview:clientOverview,meals:mealsView,progress:progressView},dietitian:{overview:dietitianOverview,clients:clientsView,builder:builderView,recipes:recipesView},admin:{overview:adminOverview,enquiries:enquiriesView,clients:clientsView,builder:builderView,recipes:recipesView}};portalContent.innerHTML=(renderers[activeRole][currentView]||noView)();portalLabel.textContent=activeRole.toUpperCase()+' SPACE';portalBreadcrumb.textContent=`${activeRole[0].toUpperCase()+activeRole.slice(1)} portal / ${roleMenu[activeRole].find(x=>x[0]===currentView)?.[1]||'Overview'}`;portalNav.innerHTML=roleMenu[activeRole].map(([id,label])=>`<button class="side-link ${currentView===id?'active':''}" onclick="setView('${id}')"><span>${icons[id]}</span>${label}</button>`).join('');$$('[data-role]').forEach(button=>button.classList.toggle('active',button.dataset.role===activeRole))}
function setView(view){currentView=view;renderPortal();$('.portal-main').scrollTo({top:0,behavior:'smooth'})}
window.setView=setView;
window.startRecipeDrag=(event,id)=>event.dataTransfer.setData('recipeId',id);
window.dropRecipe=(event,zone)=>{event.preventDefault();const recipe=recipes.find(item=>item.id===event.dataTransfer.getData('recipeId'));if(!recipe)return;zone.classList.remove('over');zone.classList.add('filled');zone.innerHTML=`<strong>${recipe.name}</strong><span>${recipe.meal} · ${recipe.time}</span>`;};
window.addMealRow=()=>{$('#scheduleList')?.insertAdjacentHTML('beforeend',scheduleRow(['New meal','12:00 PM','Lunch',''],Date.now()));};
window.filterRecipes=(value)=>{$$('#recipeRailList .recipe-card').forEach(card=>card.classList.toggle('hidden',!card.innerText.toLowerCase().includes(value.toLowerCase())))};
window.showRecipeForm=()=>$('#recipeCreator')?.classList.remove('hidden');
window.hideRecipeForm=()=>$('#recipeCreator')?.classList.add('hidden');
window.saveRecipe=(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);const name=form.get('recipeName');recipes.unshift({id:`recipe-${Date.now()}`,emoji:'🍽️',name,meal:form.get('mealType'),time:form.get('prepTime'),tags:['Team recipe']});renderPortal();};
window.publishPlan=()=>alert('Weekly plan published! Priya can now see it in her client portal.');
window.moveLead=(event,column)=>{event.preventDefault();const markup=event.dataTransfer.getData('text');if(markup){column.insertAdjacentHTML('beforeend',markup);if(column.dataset.stage==='Follow-up') alert('Follow-up scheduled: choose a date, time, note, and dietitian in the next step.');}};

$('#loginButton').addEventListener('click',()=>{activeRole='client';currentView='overview';app.classList.add('hidden');portal.classList.remove('hidden');renderPortal();});
$$('[data-role]').forEach(button=>button.addEventListener('click',()=>{activeRole=button.dataset.role;currentView='overview';renderPortal();}));
$('#backHome').addEventListener('click',()=>{portal.classList.add('hidden');app.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});});
$('#menuButton').addEventListener('click',()=>portal.classList.toggle('menu-open'));
$$('[data-open-enquiry]').forEach(btn=>btn.addEventListener('click',()=>$('#enquiryModal').classList.remove('hidden')));
$$('[data-close-enquiry]').forEach(btn=>btn.addEventListener('click',()=>{ $('#enquiryModal').classList.add('hidden'); resetEnquiry(); }));
let formStep=1, selectedGoal='';
function showFormStep(step){formStep=step;$$('.form-step').forEach(el=>el.classList.toggle('hidden',el.dataset.step!==String(step)));$$('.form-progress i').forEach((dot,i)=>dot.classList.toggle('active',i<step));$('#nextStep').textContent=step===3?'Send my enquiry':'Continue →';$('.modal-actions').classList.toggle('hidden',step==='success')}
function resetEnquiry(){selectedGoal='';$('#enquiryForm').reset();showFormStep(1);$$('.goal-grid button').forEach(b=>b.classList.remove('selected'))}
$$('[data-goal]').forEach(btn=>btn.addEventListener('click',()=>{selectedGoal=btn.dataset.goal;$$('[data-goal]').forEach(b=>b.classList.toggle('selected',b===btn));}));
$('#nextStep').addEventListener('click',()=>{if(formStep===1&&!selectedGoal){alert('Choose a goal to continue.');return}if(formStep===2&&!$('#enquiryForm').reportValidity())return;if(formStep===3){showFormStep('success');return}showFormStep(formStep+1)});
